
name: build-macos

on:
  # schedule:
  #   - cron: "0 0 * * 0"
  # push:
  #   branches:
  #     - main
  workflow_dispatch

jobs:
  build-macos:
    runs-on: macos-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: sh build_macos.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.zip
