
name: build-macos

on:
  # schedule:
  #   - cron: "0 0 * * 0"
  # push:
  #   branches:
  #     - main
  workflow_dispatch

jobs:
  build-macos:
    runs-on: macos-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: sh build_macos.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          draft: true
          automatic_release_tag: latest
          title: "Development Build"
          files: | 
            artifacts/*.zip
